[package]
name = "android-so-graph-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.27.2"
egui = "0.27.2"
egui_graphs = "0.20.0"
petgraph = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
